targets:
  $default:
    builders:
      reducer_extension_gen|reducer_extension:
        enabled: true

builders:
  reducer_extension_gen:
    target: ":reducer_extension_gen"
    import: "package:reducer_extension_gen/builder.dart"
    builder_factories: ["Reducer"]
    build_extensions: {".dart": ["reducer_extension_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]