name: reducer_extension_gen
version: 0.0.2
description: Automatically generating `reducer` extensions code for classes with `@actionReducer` annotation.
repository: https://github.com/julienzarka/reducer_extension
homepage: https://github.com/julienzarka/reducer_extension/tree/master/reducer_extension_gen
issue_tracker: https://github.com/julienzarka/reducer_extension/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <1.0.0"
  build: ">=1.0.0 <2.0.0"
  logging: ">=0.0.0 <1.0.0"
  source_gen: ">=0.9.0 <1.0.0"
  reducer_extension: ">=0.0.2 <2.0.0"

dev_dependencies:
  build_runner: ">=1.0.0 <2.0.0"
  build_test: "<1.0.0"
  test: "<2.0.0"
